//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbiStore.Shared.EFCore.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmbiStore.Shared.EFCore.Data.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1;Banco Do Brasil S.A (Bb)
        ///237;Bradesco S.A
        ///335;Banco Digio S.A
        ///260;Nu Pagamentos S.A (Nubank)
        ///290;Pagseguro Internet S.A
        ///323;Mercado Pago – Conta Do Mercado Livre
        ///637;Banco Sofisa S.A (Sofisa Direto)
        ///77;Banco Inter S.A
        ///341;Itaú Unibanco S.A
        ///104;Caixa Econômica Federal (Cef)
        ///33;Banco Santander Brasil S.A
        ///212;Banco Original S.A
        ///756;Bancoob (Banco Cooperativo Do Brasil)
        ///655;Banco Votorantim S.A
        ///41;Banrisul – Banco Do Estado Do Rio Grande Do Sul S.A
        ///389;Banco Mercantil Do Brasil S.A
        ///422;Banco S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bancos_fev_2020 {
            get {
                return ResourceManager.GetString("bancos_fev_2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;TB_CFOP_SIS&gt;
        ///  &lt;DATA_RECORD&gt;
        ///    &lt;CFOP&gt;1101&lt;/CFOP&gt;
        ///    &lt;DESCRICAO&gt;Compra para industrialização&lt;/DESCRICAO&gt;
        ///    &lt;RESUMO&gt;Compra para industrialização&lt;/RESUMO&gt;
        ///    &lt;OBSERVACAO&gt;&lt;/OBSERVACAO&gt;
        ///    &lt;EST_BX&gt;A&lt;/EST_BX&gt;
        ///    &lt;EST_BX_AMBOS&gt;S&lt;/EST_BX_AMBOS&gt;
        ///    &lt;DEV_RET&gt;N&lt;/DEV_RET&gt;
        ///    &lt;TRI_PDV_DT_UPD&gt;&lt;/TRI_PDV_DT_UPD&gt;
        ///  &lt;/DATA_RECORD&gt;
        ///  &lt;DATA_RECORD&gt;
        ///    &lt;CFOP&gt;1102&lt;/CFOP&gt;
        ///    &lt;DESCRICAO&gt;Compra para comercialização&lt;/DESCRICAO&gt;
        ///    &lt;RESUMO&gt;Compra par [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cfopseed_temp {
            get {
                return ResourceManager.GetString("cfopseed_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;TB_CSOSN_SIS&gt;
        ///	&lt;CSOSN_RECORD&gt;
        ///		&lt;CSOSN_COD&gt;101&lt;/CSOSN_COD&gt;
        ///		&lt;DESCRICAO&gt;Com permissÃ£o de crÃ©dito - OperaÃ§Ãµes que permitem a indicaÃ§Ã£o da alÃ­quota do ICMS devido  no SN e o valor do crÃ©dito correspondente.&lt;/DESCRICAO&gt;
        ///	&lt;/CSOSN_RECORD&gt;
        ///	&lt;CSOSN_RECORD&gt;
        ///		&lt;CSOSN_COD&gt;102&lt;/CSOSN_COD&gt;
        ///		&lt;DESCRICAO&gt;Sem permissÃ£o de crÃ©dito - OperaÃ§Ãµes que nÃ£o permitem a indicaÃ§Ã£o da alÃ­quota do ICMS devido no SN e do valor do crÃ©dito, e nÃ£o estejam abrangidas nos cÃ³digos 103, 203,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string csosnseed_temp {
            get {
                return ResourceManager.GetString("csosnseed_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;TB_CST_SIS&gt;
        ///  &lt;CST_RECORD&gt;
        ///    &lt;COD_CST&gt;000&lt;/COD_CST&gt;
        ///    &lt;DESCRICAO&gt;Nacional, exceto as indicados nos cÃ³digos 3 a 5 - Tributada integralmente;&lt;/DESCRICAO&gt;
        ///  &lt;/CST_RECORD&gt;
        ///  &lt;CST_RECORD&gt;
        ///    &lt;COD_CST&gt;010&lt;/COD_CST&gt;
        ///    &lt;DESCRICAO&gt;Nacional, exceto as indicados nos cÃ³digos 3 a 5 - Tributada e com cobranÃ§a do ICMS por SubstituiÃ§Ã£o TributÃ¡ria;&lt;/DESCRICAO&gt;
        ///  &lt;/CST_RECORD&gt;
        ///  &lt;CST_RECORD&gt;
        ///    &lt;COD_CST&gt;020&lt;/COD_CST&gt;
        ///    &lt;DESCRICAO&gt;Nacional, e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cstseed_temp {
            get {
                return ResourceManager.GetString("cstseed_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;municipios&gt;
        ///  &lt;municipio&gt;
        ///    &lt;ID_Municipio&gt;1100015&lt;/ID_Municipio&gt;
        ///    &lt;Mun_Desc&gt;Alta Floresta D&apos;Oeste&lt;/Mun_Desc&gt;
        ///    &lt;UF&gt;RO&lt;/UF&gt;
        ///  &lt;/municipio&gt;
        ///  &lt;municipio&gt;
        ///    &lt;ID_Municipio&gt;1100379&lt;/ID_Municipio&gt;
        ///    &lt;Mun_Desc&gt;Alto Alegre dos Parecis&lt;/Mun_Desc&gt;
        ///    &lt;UF&gt;RO&lt;/UF&gt;
        ///  &lt;/municipio&gt;
        ///  &lt;municipio&gt;
        ///    &lt;ID_Municipio&gt;1100403&lt;/ID_Municipio&gt;
        ///    &lt;Mun_Desc&gt;Alto Paraíso&lt;/Mun_Desc&gt;
        ///    &lt;UF&gt;RO&lt;/UF&gt;
        ///  &lt;/municipio&gt;
        ///  &lt;municipio&gt;
        ///    &lt;ID_Municipio&gt;1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string munseed_temp {
            get {
                return ResourceManager.GetString("munseed_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;SELECT_FROM_TB_PLANO_CONTAS&gt;
        ///  &lt;DATA_RECORD&gt;
        ///    &lt;ID_CTAPLA&gt;1&lt;/ID_CTAPLA&gt;
        ///    &lt;DESCRICAO&gt;ATIVO&lt;/DESCRICAO&gt;
        ///    &lt;COD_SPED&gt;1.&lt;/COD_SPED&gt;
        ///    &lt;COD_CONTA&gt;1.&lt;/COD_CONTA&gt;
        ///    &lt;COD_PAI&gt;&lt;/COD_PAI&gt;
        ///  &lt;/DATA_RECORD&gt;
        ///  &lt;DATA_RECORD&gt;
        ///    &lt;ID_CTAPLA&gt;2&lt;/ID_CTAPLA&gt;
        ///    &lt;DESCRICAO&gt;CIRCULANTE&lt;/DESCRICAO&gt;
        ///    &lt;COD_SPED&gt;1.01&lt;/COD_SPED&gt;
        ///    &lt;COD_CONTA&gt;1.01&lt;/COD_CONTA&gt;
        ///    &lt;COD_PAI&gt;1.&lt;/COD_PAI&gt;
        ///  &lt;/DATA_RECORD&gt;
        ///  &lt;DATA_RECORD&gt;
        ///    &lt;ID_CTAPLA&gt;3&lt;/ID_CTAPLA&gt;
        ///    &lt;DESCRICAO&gt;DISPONIBILIDADES [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string planoctaseed_temp {
            get {
                return ResourceManager.GetString("planoctaseed_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;SELECT_FROM_TB_TAXA_UF_ttu_&gt;
        ///  &lt;DATA_RECORD1&gt;
        ///    &lt;ID_CTI&gt;T00&lt;/ID_CTI&gt;
        ///    &lt;DESCRICAO&gt;Alíquota 00 do ECF&lt;/DESCRICAO&gt;
        ///    &lt;BASE_ICMS&gt;&lt;/BASE_ICMS&gt;
        ///    &lt;BASE_ICMSFE&gt;&lt;/BASE_ICMSFE&gt;
        ///    &lt;BASE_ICMS_ST&gt;&lt;/BASE_ICMS_ST&gt;
        ///    &lt;UF_AC&gt;&lt;/UF_AC&gt;
        ///    &lt;UF_AL&gt;&lt;/UF_AL&gt;
        ///    &lt;UF_AM&gt;&lt;/UF_AM&gt;
        ///    &lt;UF_AP&gt;&lt;/UF_AP&gt;
        ///    &lt;UF_BA&gt;&lt;/UF_BA&gt;
        ///    &lt;UF_CE&gt;&lt;/UF_CE&gt;
        ///    &lt;UF_DF&gt;&lt;/UF_DF&gt;
        ///    &lt;UF_ES&gt;&lt;/UF_ES&gt;
        ///    &lt;UF_GO&gt;&lt;/UF_GO&gt;
        ///    &lt;UF_MA&gt;&lt;/UF_MA&gt;
        ///    &lt;UF_MG&gt;&lt;/UF_MG&gt;
        ///    &lt;UF_MS&gt;&lt;/UF_MS&gt;
        ///    &lt;UF_MT&gt;&lt;/UF_M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string taxasseed_temp {
            get {
                return ResourceManager.GetString("taxasseed_temp", resourceCulture);
            }
        }
    }
}
